name: Deploy

on:
  push:
    branches: [main]

jobs:
  test-before-deploy:
    name: Test Before Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build check
        run: npm run build
        env:
          SKIP_ENV_VALIDATION: true

      - name: ✅ Tests passed - Safe to deploy
        run: echo "All tests passed! Vercel will auto-deploy."

